import json
from datetime import datetime


def display_summary(
    failed_attempts,
    failed_ips,
    targeted_users,
    ip_targeted_users
):
    """
    Display a summary of failed-login activity.
    """

    print("=== SECURITY LOG ANALYZER ===")
    print()

    print("Total failed login attempts:", failed_attempts)

    print("\n=== FAILED ATTEMPTS BY IP ===")

    for ip, count in failed_ips.items():
        print(ip, "->", count, "failed attempts")

    print("\n=== TARGETED ACCOUNTS ===")

    for username, count in targeted_users.items():
        print(username, "->", count, "failed attempts")

    print("\n=== IP TO USER CORRELATION ===")

    for ip, users in ip_targeted_users.items():
        print("Source IP:", ip)
        print("Unique accounts targeted:", len(users))
        print("Accounts:", ", ".join(sorted(users)))
        print()


def display_alerts(
    repeated_login_alerts,
    account_targeting_alerts,
    login_burst_alerts
):
    """
    Display security alerts generated by the detection engine.
    """

    print("=== REPEATED LOGIN ALERTS ===")

    for alert in repeated_login_alerts:
        print("[{} ALERT]".format(alert["severity"]))
        print("Source IP:", alert["ip_address"])
        print("Failed attempts:", alert["failed_attempts"])
        print("Threshold:", alert["threshold"])
        print()

    print("=== ACCOUNT TARGETING ALERTS ===")

    for alert in account_targeting_alerts:
        print("[SUSPICIOUS ACCOUNT TARGETING]")
        print("Source IP:", alert["ip_address"])
        print("Unique accounts:", alert["unique_accounts"])
        print("Accounts:", ", ".join(alert["accounts"]))
        print()

    print("=== LOGIN BURST ALERTS ===")

    for alert in login_burst_alerts:
        print("[SUSPICIOUS LOGIN BURST]")
        print("Source IP:", alert["ip_address"])
        print("Failed attempts:", alert["attempts"])
        print(
            "Time window:",
            alert["window_seconds"],
            "seconds"
        )
        print(
            "Window started:",
            alert["window_start"].strftime("%H:%M:%S")
        )
        print()


def save_json_report(
    failed_attempts,
    failed_ips,
    targeted_users,
    ip_targeted_users,
    repeated_login_alerts,
    account_targeting_alerts,
    login_burst_alerts,
    output_file="reports/security_report.json"
):
    """
    Save analysis results and security alerts
    to a JSON report file.
    """

    report = {
        "generated_at": datetime.now().isoformat(),
        "summary": {
            "total_failed_attempts": failed_attempts,
            "failed_attempts_by_ip": failed_ips,
            "targeted_accounts": targeted_users,
            "ip_to_user_correlation": {
                ip: sorted(users)
                for ip, users in ip_targeted_users.items()
            }
        },
        "alerts": {
            "repeated_login": repeated_login_alerts,
            "account_targeting": account_targeting_alerts,
            "login_burst": []
        }
    }

    # Convert datetime objects into text for JSON
    for alert in login_burst_alerts:
        alert_copy = alert.copy()

        alert_copy["window_start"] = (
            alert_copy["window_start"].isoformat()
        )

        report["alerts"]["login_burst"].append(
            alert_copy
        )

    with open(output_file, "w") as file:
        json.dump(
            report,
            file,
            indent=4
        )

    print(
        "JSON security report saved to:",
        output_file
    )